// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeLoginCode = `-- name: ConsumeLoginCode :execrows
UPDATE login_codes SET consumed_at = $2
WHERE id = $1 AND consumed_at IS NULL
`

type ConsumeLoginCodeParams struct {
	ID         pgtype.UUID
	ConsumedAt pgtype.Timestamptz
}

// Single use, enforced by the WHERE rather than by the caller: two requests
// racing with the same correct code produce one winner.
func (q *Queries) ConsumeLoginCode(ctx context.Context, arg ConsumeLoginCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeLoginCode, arg.ID, arg.ConsumedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCodesForEmail = `-- name: CountCodesForEmail :one
SELECT count(*) FROM login_codes
WHERE email = $1 AND created_at > $2
`

type CountCodesForEmailParams struct {
	Email     string
	CreatedAt pgtype.Timestamptz
}

// The per-address rate limit: how many codes has this address asked for
// recently? Counting requests rather than tracking a bucket keeps the limit in
// the same table as the thing it limits, and moves with the injected clock.
func (q *Queries) CountCodesForEmail(ctx context.Context, arg CountCodesForEmailParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCodesForEmail, arg.Email, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCodesForIP = `-- name: CountCodesForIP :one
SELECT count(*) FROM login_codes
WHERE requested_ip = $1 AND created_at > $2
`

type CountCodesForIPParams struct {
	RequestedIp *netip.Addr
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CountCodesForIP(ctx context.Context, arg CountCodesForIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCodesForIP, arg.RequestedIp, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (token_hash, user_id, created_at, expires_at, last_seen_at)
VALUES ($1, $2, $3, $4, $3)
`

type CreateAuthSessionParams struct {
	TokenHash []byte
	UserID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	ExpiresAt pgtype.Timestamptz
}

// last_seen_at starts equal to created_at; it is the expiry that is the
// interesting column, and it is passed in rather than computed here so the
// lifetime lives in one place in Go.
func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession,
		arg.TokenHash,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const createLoginCode = `-- name: CreateLoginCode :one
INSERT INTO login_codes (email, code_hash, requested_ip, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, code_hash, requested_ip, created_at, expires_at, attempts, consumed_at
`

type CreateLoginCodeParams struct {
	Email       string
	CodeHash    []byte
	RequestedIp *netip.Addr
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateLoginCode(ctx context.Context, arg CreateLoginCodeParams) (LoginCode, error) {
	row := q.db.QueryRow(ctx, createLoginCode,
		arg.Email,
		arg.CodeHash,
		arg.RequestedIp,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	var i LoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.RequestedIp,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
	)
	return i, err
}

const deleteAuthSession = `-- name: DeleteAuthSession :exec
DELETE FROM auth_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteAuthSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteAuthSession, tokenHash)
	return err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :exec
DELETE FROM auth_sessions WHERE expires_at <= $1
`

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthSessions, expiresAt)
	return err
}

const liveCodeForEmail = `-- name: LiveCodeForEmail :one
SELECT id, email, code_hash, requested_ip, created_at, expires_at, attempts, consumed_at FROM login_codes
WHERE email = $1 AND consumed_at IS NULL AND expires_at > $2
ORDER BY created_at DESC
LIMIT 1
`

type LiveCodeForEmailParams struct {
	Email     string
	ExpiresAt pgtype.Timestamptz
}

// The one code that could still be verified: unconsumed and unexpired.
func (q *Queries) LiveCodeForEmail(ctx context.Context, arg LiveCodeForEmailParams) (LoginCode, error) {
	row := q.db.QueryRow(ctx, liveCodeForEmail, arg.Email, arg.ExpiresAt)
	var i LoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.RequestedIp,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
	)
	return i, err
}

const recordFailedAttempt = `-- name: RecordFailedAttempt :one
UPDATE login_codes
SET attempts = attempts + 1,
    consumed_at = CASE WHEN attempts + 1 >= $2 THEN $3 ELSE consumed_at END
WHERE id = $1
RETURNING id, email, code_hash, requested_ip, created_at, expires_at, attempts, consumed_at
`

type RecordFailedAttemptParams struct {
	ID         pgtype.UUID
	Attempts   int32
	ConsumedAt pgtype.Timestamptz
}

// One wrong guess. Consuming the row at the limit is done in the same
// statement so that concurrent guesses cannot both see "one attempt left".
func (q *Queries) RecordFailedAttempt(ctx context.Context, arg RecordFailedAttemptParams) (LoginCode, error) {
	row := q.db.QueryRow(ctx, recordFailedAttempt, arg.ID, arg.Attempts, arg.ConsumedAt)
	var i LoginCode
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.RequestedIp,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Attempts,
		&i.ConsumedAt,
	)
	return i, err
}

const supersedeCodesForEmail = `-- name: SupersedeCodesForEmail :exec
UPDATE login_codes SET consumed_at = $2
WHERE email = $1 AND consumed_at IS NULL
`

type SupersedeCodesForEmailParams struct {
	Email      string
	ConsumedAt pgtype.Timestamptz
}

// Asking for a new code kills the old one. Two live codes for one address
// would mean the older email in an inbox still works, which is the thing the
// expiry exists to prevent.
func (q *Queries) SupersedeCodesForEmail(ctx context.Context, arg SupersedeCodesForEmailParams) error {
	_, err := q.db.Exec(ctx, supersedeCodesForEmail, arg.Email, arg.ConsumedAt)
	return err
}

const touchAuthSession = `-- name: TouchAuthSession :exec
UPDATE auth_sessions SET last_seen_at = $2, expires_at = $3
WHERE token_hash = $1
`

type TouchAuthSessionParams struct {
	TokenHash  []byte
	LastSeenAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

// The sliding expiry. Written on use rather than on a schedule, so a session
// that is being used never lapses and one that is not eventually does.
func (q *Queries) TouchAuthSession(ctx context.Context, arg TouchAuthSessionParams) error {
	_, err := q.db.Exec(ctx, touchAuthSession, arg.TokenHash, arg.LastSeenAt, arg.ExpiresAt)
	return err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email, created_at)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, handle, created_at, handle_set_at
`

type UpsertUserByEmailParams struct {
	Email     string
	CreatedAt pgtype.Timestamptz
}

// One flow, not two: an unknown address creates the account, a known one
// signs in. The DO UPDATE is a no-op that exists only so RETURNING fires on
// the conflict path too.
func (q *Queries) UpsertUserByEmail(ctx context.Context, arg UpsertUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, arg.Email, arg.CreatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.CreatedAt,
		&i.HandleSetAt,
	)
	return i, err
}

const userForSession = `-- name: UserForSession :one
SELECT users.id, users.email, users.handle, users.created_at, users.handle_set_at, auth_sessions.expires_at
FROM auth_sessions
JOIN users ON users.id = auth_sessions.user_id
WHERE auth_sessions.token_hash = $1 AND auth_sessions.expires_at > $2
`

type UserForSessionParams struct {
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

type UserForSessionRow struct {
	User      User
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UserForSession(ctx context.Context, arg UserForSessionParams) (UserForSessionRow, error) {
	row := q.db.QueryRow(ctx, userForSession, arg.TokenHash, arg.ExpiresAt)
	var i UserForSessionRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Email,
		&i.User.Handle,
		&i.User.CreatedAt,
		&i.User.HandleSetAt,
		&i.ExpiresAt,
	)
	return i, err
}
