// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryByID = `-- name: CategoryByID :one
SELECT id, user_id, name, is_public, created_at, updated_at, deleted_at FROM categories WHERE id = $1 AND user_id = $2
`

type CategoryByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

// Tombstones included: a caller editing a category that was deleted on another
// device needs to be told it is gone, not told it never existed.
func (q *Queries) CategoryByID(ctx context.Context, arg CategoryByIDParams) (Category, error) {
	row := q.db.QueryRow(ctx, categoryByID, arg.ID, arg.UserID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (id, user_id, name, is_public, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $5)
ON CONFLICT (id) DO UPDATE SET id = categories.id
RETURNING id, user_id, name, is_public, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	IsPublic  bool
	CreatedAt pgtype.Timestamptz
}

// Idempotent on the client-minted id: a retry returns the row the first
// attempt made rather than making a second one. The DO UPDATE is a no-op that
// exists only so RETURNING fires on the conflict path too.
func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.IsPublic,
		arg.CreatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
UPDATE categories SET deleted_at = $3, updated_at = $3
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type DeleteCategoryParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	DeletedAt pgtype.Timestamptz
}

// A tombstone. Deleting one that is already deleted is not an error — the
// caller asked for a state, and the state is what it gets.
func (q *Queries) DeleteCategory(ctx context.Context, arg DeleteCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, arg.ID, arg.UserID, arg.DeletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const liveCategories = `-- name: LiveCategories :many
SELECT id, user_id, name, is_public, created_at, updated_at, deleted_at FROM categories
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at
`

func (q *Queries) LiveCategories(ctx context.Context, userID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, liveCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.IsPublic,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories SET name = $3, is_public = $4, updated_at = $5
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, is_public, created_at, updated_at, deleted_at
`

type UpdateCategoryParams struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	IsPublic  bool
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.IsPublic,
		arg.UpdatedAt,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.IsPublic,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
