// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type SessionKind string

const (
	SessionKindWork       SessionKind = "work"
	SessionKindShortBreak SessionKind = "short_break"
	SessionKindLongBreak  SessionKind = "long_break"
)

func (e *SessionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionKind(s)
	case string:
		*e = SessionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionKind: %T", src)
	}
	return nil
}

type NullSessionKind struct {
	SessionKind SessionKind
	Valid       bool // Valid is true if SessionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionKind) Scan(value interface{}) error {
	if value == nil {
		ns.SessionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionKind), nil
}

type AuthSession struct {
	TokenHash  []byte
	UserID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type Category struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Name      string
	IsPublic  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type LoginCode struct {
	ID          pgtype.UUID
	Email       string
	CodeHash    []byte
	RequestedIp *netip.Addr
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	Attempts    int32
	ConsumedAt  pgtype.Timestamptz
}

type PushSubscription struct {
	Endpoint  string
	UserID    pgtype.UUID
	P256dh    string
	Auth      string
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Kind         SessionKind
	CategoryID   pgtype.UUID
	StartedAt    pgtype.Timestamptz
	DurationMs   int64
	EndsAt       pgtype.Timestamptz
	ConfirmedAt  pgtype.Timestamptz
	CancelledAt  pgtype.Timestamptz
	ShortBreakMs *int64
	LongBreakMs  *int64
}

type User struct {
	ID           pgtype.UUID
	Email        string
	Handle       *string
	CreatedAt    pgtype.Timestamptz
	HandleSetAt  pgtype.Timestamptz
	ShortBreakMs int64
	LongBreakMs  int64
	PerCycle     int32
}
