// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthSession struct {
	TokenHash  []byte
	UserID     pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	LastSeenAt pgtype.Timestamptz
}

type LoginCode struct {
	ID          pgtype.UUID
	Email       string
	CodeHash    []byte
	RequestedIp *netip.Addr
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	Attempts    int32
	ConsumedAt  pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	Email       string
	Handle      *string
	CreatedAt   pgtype.Timestamptz
	HandleSetAt pgtype.Timestamptz
}
