// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM push_subscriptions WHERE endpoint = $1
`

// By endpoint alone, with no user_id: this is what the push service reporting
// "gone" turns into, and by then the row's owner is beside the point. The
// endpoint is unguessable and belongs to whoever holds it, which is the same
// thing that makes it safe as the key.
func (q *Queries) DeleteSubscription(ctx context.Context, endpoint string) error {
	_, err := q.db.Exec(ctx, deleteSubscription, endpoint)
	return err
}

const pendingBells = `-- name: PendingBells :many
SELECT id, user_id, kind, ends_at FROM sessions
WHERE confirmed_at IS NULL AND cancelled_at IS NULL AND ends_at > $1
ORDER BY ends_at
`

type PendingBellsRow struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
	Kind   SessionKind
	EndsAt pgtype.Timestamptz
}

// Every bell that has not rung yet, across all accounts, for the in-memory
// timers to be rebuilt from at boot.
//
// Bounded by `ends_at > $1` on purpose: a bell that went while the process was
// down has already been missed, and a notification for it now would be an
// alarm about something that finished during the restart. Nothing is written
// here and nothing is written when one of these fires — the timer is a
// courtesy laid over state that is still derived from the rows themselves.
func (q *Queries) PendingBells(ctx context.Context, endsAt pgtype.Timestamptz) ([]PendingBellsRow, error) {
	rows, err := q.db.Query(ctx, pendingBells, endsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingBellsRow
	for rows.Next() {
		var i PendingBellsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveSubscription = `-- name: SaveSubscription :exec
INSERT INTO push_subscriptions (endpoint, user_id, p256dh, auth, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (endpoint) DO UPDATE
    SET user_id = excluded.user_id,
        p256dh  = excluded.p256dh,
        auth    = excluded.auth
`

type SaveSubscriptionParams struct {
	Endpoint  string
	UserID    pgtype.UUID
	P256dh    string
	Auth      string
	CreatedAt pgtype.Timestamptz
}

// Idempotent on the endpoint, which is the device's own name for itself. A tab
// that re-subscribes on every load writes the same row every time, and a shared
// browser that is now somebody else's moves it to them.
func (q *Queries) SaveSubscription(ctx context.Context, arg SaveSubscriptionParams) error {
	_, err := q.db.Exec(ctx, saveSubscription,
		arg.Endpoint,
		arg.UserID,
		arg.P256dh,
		arg.Auth,
		arg.CreatedAt,
	)
	return err
}

const subscriptionsForUser = `-- name: SubscriptionsForUser :many
SELECT endpoint, p256dh, auth FROM push_subscriptions WHERE user_id = $1
`

type SubscriptionsForUserRow struct {
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) SubscriptionsForUser(ctx context.Context, userID pgtype.UUID) ([]SubscriptionsForUserRow, error) {
	rows, err := q.db.Query(ctx, subscriptionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionsForUserRow
	for rows.Next() {
		var i SubscriptionsForUserRow
		if err := rows.Scan(&i.Endpoint, &i.P256dh, &i.Auth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
