// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSession = `-- name: CancelSession :execrows
UPDATE sessions SET cancelled_at = $3
WHERE id = $1 AND user_id = $2
  AND confirmed_at IS NULL AND cancelled_at IS NULL
  AND ends_at > $3
`

type CancelSessionParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	CancelledAt pgtype.Timestamptz
}

// Only while it is still running: once the bell has gone the work has been
// credited, and credited work cannot be retracted.
func (q *Queries) CancelSession(ctx context.Context, arg CancelSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSession, arg.ID, arg.UserID, arg.CancelledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmSession = `-- name: ConfirmSession :execrows
UPDATE sessions SET confirmed_at = $3
WHERE id = $1 AND user_id = $2
  AND confirmed_at IS NULL AND cancelled_at IS NULL
  AND ends_at <= $3
`

type ConfirmSessionParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	ConfirmedAt pgtype.Timestamptz
}

// Only once the bell has gone, and only ever this one column. The work was
// credited at its exact nominal end, so what this records is the
// acknowledgement and nothing else: confirming in two seconds and confirming
// in two hours write the same history.
func (q *Queries) ConfirmSession(ctx context.Context, arg ConfirmSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmSession, arg.ID, arg.UserID, arg.ConfirmedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const creditedBetween = `-- name: CreditedBetween :one
SELECT count(*)::bigint AS count, coalesce(sum(duration_ms), 0)::bigint AS total_ms
FROM sessions
WHERE user_id = $1
  AND kind = 'work'
  AND cancelled_at IS NULL
  AND ends_at >= $2
  AND ends_at <= $3
`

type CreditedBetweenParams struct {
	UserID   pgtype.UUID
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type CreditedBetweenRow struct {
	Count   int64
	TotalMs int64
}

// What has been credited in a window: how many pomodoros, and how long they
// were worth.
//
// Bounded by `ends_at` rather than `started_at`, because that is when work is
// credited. A pomodoro that began before Tehran midnight and rang after it
// belongs to the new day, and one whose bell has gone counts immediately —
// confirming it is an acknowledgement and moves nothing.
//
// `duration_ms` rather than the wall time between the two timestamps: the
// nominal length is what is credited, and under FAST_SESSIONS those are not
// the same number.
func (q *Queries) CreditedBetween(ctx context.Context, arg CreditedBetweenParams) (CreditedBetweenRow, error) {
	row := q.db.QueryRow(ctx, creditedBetween, arg.UserID, arg.FromTime, arg.ToTime)
	var i CreditedBetweenRow
	err := row.Scan(&i.Count, &i.TotalMs)
	return i, err
}

const creditedWorkBetween = `-- name: CreditedWorkBetween :many
SELECT ends_at, duration_ms FROM sessions
WHERE user_id = $1
  AND kind = 'work'
  AND cancelled_at IS NULL
  AND ends_at >= $2
  AND ends_at <= $3
ORDER BY ends_at
`

type CreditedWorkBetweenParams struct {
	UserID   pgtype.UUID
	FromTime pgtype.Timestamptz
	ToTime   pgtype.Timestamptz
}

type CreditedWorkBetweenRow struct {
	EndsAt     pgtype.Timestamptz
	DurationMs int64
}

// The credited pomodoros in a window, for the chart to be built from.
//
// Rows rather than a GROUP BY, because the grouping is by *Tehran* day and that
// boundary lives in the domain package — a second definition of it in SQL would
// be a second thing to get wrong, and this one would depend on the database's
// own timezone data rather than the tzdata the binary embeds. The volume is a
// few hundred rows over ninety days of heavy use, which is nothing to carry.
//
// Bounded by `ends_at`, like every other read of credited work: it is when the
// bell went, and a pomodoro that began before Tehran midnight and rang after it
// belongs to the day it was credited in.
func (q *Queries) CreditedWorkBetween(ctx context.Context, arg CreditedWorkBetweenParams) ([]CreditedWorkBetweenRow, error) {
	rows, err := q.db.Query(ctx, creditedWorkBetween, arg.UserID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditedWorkBetweenRow
	for rows.Next() {
		var i CreditedWorkBetweenRow
		if err := rows.Scan(&i.EndsAt, &i.DurationMs); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasLiveSessionForCategory = `-- name: HasLiveSessionForCategory :one
SELECT EXISTS (
    SELECT 1 FROM sessions
    WHERE user_id = $1 AND category_id = $2
      AND confirmed_at IS NULL AND cancelled_at IS NULL
)
`

type HasLiveSessionForCategoryParams struct {
	UserID     pgtype.UUID
	CategoryID pgtype.UUID
}

// The guard on editing a task out from under a session that is using it.
func (q *Queries) HasLiveSessionForCategory(ctx context.Context, arg HasLiveSessionForCategoryParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLiveSessionForCategory, arg.UserID, arg.CategoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const liveFeed = `-- name: LiveFeed :many
SELECT users.handle, sessions.kind, sessions.started_at, sessions.ends_at,
       categories.name AS category_name, categories.is_public AS category_is_public
FROM sessions
JOIN users ON users.id = sessions.user_id
LEFT JOIN categories ON categories.id = sessions.category_id
WHERE sessions.confirmed_at IS NULL
  AND sessions.cancelled_at IS NULL
  AND sessions.ends_at > $1
  AND users.handle IS NOT NULL
ORDER BY sessions.started_at DESC
`

type LiveFeedRow struct {
	Handle           *string
	Kind             SessionKind
	StartedAt        pgtype.Timestamptz
	EndsAt           pgtype.Timestamptz
	CategoryName     *string
	CategoryIsPublic *bool
}

// Everybody working right now, across all accounts.
//
// A query over the sessions themselves rather than an advisory "who is online"
// table, so it cannot go stale and cannot disagree with the timer it describes.
// The partial index on (ends_at) where the session is live is what makes that
// affordable.
//
// `ends_at > @now` is how somebody leaves the feed at their bell rather than at
// the tap that acknowledges it: ring time is not work, and advertising it as
// work would be advertising a pomodoro that finished twenty minutes ago.
//
// An account with no handle yet is nobody the feed can name, so it is not in it.
// The category's name and its visibility both come back; deciding what a
// stranger may read is the application's job and not this query's.
func (q *Queries) LiveFeed(ctx context.Context, now pgtype.Timestamptz) ([]LiveFeedRow, error) {
	rows, err := q.db.Query(ctx, liveFeed, now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveFeedRow
	for rows.Next() {
		var i LiveFeedRow
		if err := rows.Scan(
			&i.Handle,
			&i.Kind,
			&i.StartedAt,
			&i.EndsAt,
			&i.CategoryName,
			&i.CategoryIsPublic,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveSessionForUser = `-- name: LiveSessionForUser :one
SELECT sessions.id, sessions.user_id, sessions.kind, sessions.category_id, sessions.started_at, sessions.duration_ms, sessions.ends_at, sessions.confirmed_at, sessions.cancelled_at, sessions.short_break_ms, sessions.long_break_ms, categories.name AS category_name, categories.is_public AS category_is_public
FROM sessions
LEFT JOIN categories ON categories.id = sessions.category_id
WHERE sessions.user_id = $1
  AND sessions.confirmed_at IS NULL
  AND sessions.cancelled_at IS NULL
`

type LiveSessionForUserRow struct {
	Session          Session
	CategoryName     *string
	CategoryIsPublic *bool
}

// The one session that has not been acknowledged or abandoned. It may be
// running or ringing; which of those it is, is a question for the clock and
// not for the database.
func (q *Queries) LiveSessionForUser(ctx context.Context, userID pgtype.UUID) (LiveSessionForUserRow, error) {
	row := q.db.QueryRow(ctx, liveSessionForUser, userID)
	var i LiveSessionForUserRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.Kind,
		&i.Session.CategoryID,
		&i.Session.StartedAt,
		&i.Session.DurationMs,
		&i.Session.EndsAt,
		&i.Session.ConfirmedAt,
		&i.Session.CancelledAt,
		&i.Session.ShortBreakMs,
		&i.Session.LongBreakMs,
		&i.CategoryName,
		&i.CategoryIsPublic,
	)
	return i, err
}

const sessionByID = `-- name: SessionByID :one
SELECT id, user_id, kind, category_id, started_at, duration_ms, ends_at, confirmed_at, cancelled_at, short_break_ms, long_break_ms FROM sessions WHERE id = $1 AND user_id = $2
`

type SessionByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SessionByID(ctx context.Context, arg SessionByIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByID, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CategoryID,
		&i.StartedAt,
		&i.DurationMs,
		&i.EndsAt,
		&i.ConfirmedAt,
		&i.CancelledAt,
		&i.ShortBreakMs,
		&i.LongBreakMs,
	)
	return i, err
}

const sessionsSince = `-- name: SessionsSince :many
SELECT id, user_id, kind, category_id, started_at, duration_ms, ends_at, confirmed_at, cancelled_at, short_break_ms, long_break_ms FROM sessions
WHERE user_id = $1 AND started_at >= $2
ORDER BY started_at
`

type SessionsSinceParams struct {
	UserID    pgtype.UUID
	StartedAt pgtype.Timestamptz
}

// The recent past the cycle counter is walked out of, oldest first.
//
// Nothing stores the count: it is derived from these rows plus now(), like
// every other piece of session state. The window only has to be wider than a
// cycle can be — an hour of idleness ends one, and a long break every few
// pomodoros ends one — so a day is many times over enough.
func (q *Queries) SessionsSince(ctx context.Context, arg SessionsSinceParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, sessionsSince, arg.UserID, arg.StartedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.CategoryID,
			&i.StartedAt,
			&i.DurationMs,
			&i.EndsAt,
			&i.ConfirmedAt,
			&i.CancelledAt,
			&i.ShortBreakMs,
			&i.LongBreakMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startSession = `-- name: StartSession :one
INSERT INTO sessions (id, user_id, kind, category_id, started_at, duration_ms, ends_at, short_break_ms, long_break_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET id = sessions.id
RETURNING id, user_id, kind, category_id, started_at, duration_ms, ends_at, confirmed_at, cancelled_at, short_break_ms, long_break_ms
`

type StartSessionParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	Kind         SessionKind
	CategoryID   pgtype.UUID
	StartedAt    pgtype.Timestamptz
	DurationMs   int64
	EndsAt       pgtype.Timestamptz
	ShortBreakMs *int64
	LongBreakMs  *int64
}

// Idempotent on the client-minted id. The partial unique index is what stops a
// second live session existing; this returns the row rather than erroring when
// the same start is retried.
//
// The two break lengths are the account's, as they stood at this instant. They
// are written once with the row and never touched again, which is what makes
// editing the dialog mid-session unable to change the rest this session owes.
func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, startSession,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.CategoryID,
		arg.StartedAt,
		arg.DurationMs,
		arg.EndsAt,
		arg.ShortBreakMs,
		arg.LongBreakMs,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CategoryID,
		&i.StartedAt,
		&i.DurationMs,
		&i.EndsAt,
		&i.ConfirmedAt,
		&i.CancelledAt,
		&i.ShortBreakMs,
		&i.LongBreakMs,
	)
	return i, err
}

const workBeforeBreak = `-- name: WorkBeforeBreak :one
SELECT id, user_id, kind, category_id, started_at, duration_ms, ends_at, confirmed_at, cancelled_at, short_break_ms, long_break_ms FROM sessions
WHERE user_id = $1 AND kind = 'work' AND cancelled_at IS NULL AND ends_at = $2
`

type WorkBeforeBreakParams struct {
	UserID pgtype.UUID
	EndsAt pgtype.Timestamptz
}

// The pomodoro a break was handed over from.
//
// Found by its end rather than by a foreign key, because that is what the two
// rows actually share: a break is anchored at its pomodoro's nominal end, so
// `started_at` here *is* that bell. One live session per user is what makes it
// unambiguous — two uncancelled pomodoros cannot end at the same instant.
func (q *Queries) WorkBeforeBreak(ctx context.Context, arg WorkBeforeBreakParams) (Session, error) {
	row := q.db.QueryRow(ctx, workBeforeBreak, arg.UserID, arg.EndsAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CategoryID,
		&i.StartedAt,
		&i.DurationMs,
		&i.EndsAt,
		&i.ConfirmedAt,
		&i.CancelledAt,
		&i.ShortBreakMs,
		&i.LongBreakMs,
	)
	return i, err
}
