// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSession = `-- name: CancelSession :execrows
UPDATE sessions SET cancelled_at = $3
WHERE id = $1 AND user_id = $2
  AND confirmed_at IS NULL AND cancelled_at IS NULL
  AND ends_at > $3
`

type CancelSessionParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	CancelledAt pgtype.Timestamptz
}

// Only while it is still running: once the bell has gone the work has been
// credited, and credited work cannot be retracted.
func (q *Queries) CancelSession(ctx context.Context, arg CancelSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSession, arg.ID, arg.UserID, arg.CancelledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmSession = `-- name: ConfirmSession :execrows
UPDATE sessions SET confirmed_at = $3
WHERE id = $1 AND user_id = $2
  AND confirmed_at IS NULL AND cancelled_at IS NULL
  AND ends_at <= $3
`

type ConfirmSessionParams struct {
	ID          pgtype.UUID
	UserID      pgtype.UUID
	ConfirmedAt pgtype.Timestamptz
}

// Only once the bell has gone, and only ever this one column. The work was
// credited at its exact nominal end, so what this records is the
// acknowledgement and nothing else: confirming in two seconds and confirming
// in two hours write the same history.
func (q *Queries) ConfirmSession(ctx context.Context, arg ConfirmSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmSession, arg.ID, arg.UserID, arg.ConfirmedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasLiveSessionForCategory = `-- name: HasLiveSessionForCategory :one
SELECT EXISTS (
    SELECT 1 FROM sessions
    WHERE user_id = $1 AND category_id = $2
      AND confirmed_at IS NULL AND cancelled_at IS NULL
)
`

type HasLiveSessionForCategoryParams struct {
	UserID     pgtype.UUID
	CategoryID pgtype.UUID
}

// The guard on editing a task out from under a session that is using it.
func (q *Queries) HasLiveSessionForCategory(ctx context.Context, arg HasLiveSessionForCategoryParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasLiveSessionForCategory, arg.UserID, arg.CategoryID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const liveSessionForUser = `-- name: LiveSessionForUser :one
SELECT sessions.id, sessions.user_id, sessions.kind, sessions.category_id, sessions.started_at, sessions.duration_ms, sessions.ends_at, sessions.confirmed_at, sessions.cancelled_at, categories.name AS category_name, categories.is_public AS category_is_public
FROM sessions
LEFT JOIN categories ON categories.id = sessions.category_id
WHERE sessions.user_id = $1
  AND sessions.confirmed_at IS NULL
  AND sessions.cancelled_at IS NULL
`

type LiveSessionForUserRow struct {
	Session          Session
	CategoryName     *string
	CategoryIsPublic *bool
}

// The one session that has not been acknowledged or abandoned. It may be
// running or ringing; which of those it is, is a question for the clock and
// not for the database.
func (q *Queries) LiveSessionForUser(ctx context.Context, userID pgtype.UUID) (LiveSessionForUserRow, error) {
	row := q.db.QueryRow(ctx, liveSessionForUser, userID)
	var i LiveSessionForUserRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.Kind,
		&i.Session.CategoryID,
		&i.Session.StartedAt,
		&i.Session.DurationMs,
		&i.Session.EndsAt,
		&i.Session.ConfirmedAt,
		&i.Session.CancelledAt,
		&i.CategoryName,
		&i.CategoryIsPublic,
	)
	return i, err
}

const sessionByID = `-- name: SessionByID :one
SELECT id, user_id, kind, category_id, started_at, duration_ms, ends_at, confirmed_at, cancelled_at FROM sessions WHERE id = $1 AND user_id = $2
`

type SessionByIDParams struct {
	ID     pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) SessionByID(ctx context.Context, arg SessionByIDParams) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByID, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CategoryID,
		&i.StartedAt,
		&i.DurationMs,
		&i.EndsAt,
		&i.ConfirmedAt,
		&i.CancelledAt,
	)
	return i, err
}

const startSession = `-- name: StartSession :one
INSERT INTO sessions (id, user_id, kind, category_id, started_at, duration_ms, ends_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO UPDATE SET id = sessions.id
RETURNING id, user_id, kind, category_id, started_at, duration_ms, ends_at, confirmed_at, cancelled_at
`

type StartSessionParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	Kind       SessionKind
	CategoryID pgtype.UUID
	StartedAt  pgtype.Timestamptz
	DurationMs int64
	EndsAt     pgtype.Timestamptz
}

// Idempotent on the client-minted id. The partial unique index is what stops a
// second live session existing; this returns the row rather than erroring when
// the same start is retried.
func (q *Queries) StartSession(ctx context.Context, arg StartSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, startSession,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.CategoryID,
		arg.StartedAt,
		arg.DurationMs,
		arg.EndsAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.CategoryID,
		&i.StartedAt,
		&i.DurationMs,
		&i.EndsAt,
		&i.ConfirmedAt,
		&i.CancelledAt,
	)
	return i, err
}
