// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimHandle = `-- name: ClaimHandle :one
UPDATE users SET handle = $2, handle_set_at = $3
WHERE id = $1 AND handle IS NULL
RETURNING id, email, handle, created_at, handle_set_at, short_break_ms, long_break_ms, per_cycle
`

type ClaimHandleParams struct {
	ID          pgtype.UUID
	Handle      *string
	HandleSetAt pgtype.Timestamptz
}

// Claimed once. The WHERE is what makes it once: a user who already has one
// matches nothing, so a second claim is a no-op that the caller can recognise
// rather than a silent overwrite. The trigger on the table refuses a rename
// anyway — this is the layer that gives a readable answer, not the one that
// enforces it.
func (q *Queries) ClaimHandle(ctx context.Context, arg ClaimHandleParams) (User, error) {
	row := q.db.QueryRow(ctx, claimHandle, arg.ID, arg.Handle, arg.HandleSetAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.CreatedAt,
		&i.HandleSetAt,
		&i.ShortBreakMs,
		&i.LongBreakMs,
		&i.PerCycle,
	)
	return i, err
}

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const setIntervals = `-- name: SetIntervals :one
UPDATE users SET short_break_ms = $2, long_break_ms = $3, per_cycle = $4
WHERE id = $1
RETURNING id, email, handle, created_at, handle_set_at, short_break_ms, long_break_ms, per_cycle
`

type SetIntervalsParams struct {
	ID           pgtype.UUID
	ShortBreakMs int64
	LongBreakMs  int64
	PerCycle     int32
}

// The account's intervals, replaced whole. There is nothing to merge: the
// dialog holds all three and sends all three, so a stepper tapped on a phone
// cannot quietly revert what was set on a laptop a moment ago.
//
// The bands are a CHECK on the table as well as a guard in the handler, so the
// worst a bug here can do is fail.
func (q *Queries) SetIntervals(ctx context.Context, arg SetIntervalsParams) (User, error) {
	row := q.db.QueryRow(ctx, setIntervals,
		arg.ID,
		arg.ShortBreakMs,
		arg.LongBreakMs,
		arg.PerCycle,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.CreatedAt,
		&i.HandleSetAt,
		&i.ShortBreakMs,
		&i.LongBreakMs,
		&i.PerCycle,
	)
	return i, err
}
