// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const userByHandle = `-- name: UserByHandle :one
SELECT id, email, handle, created_at, handle_set_at FROM users WHERE handle = $1
`

func (q *Queries) UserByHandle(ctx context.Context, handle *string) (User, error) {
	row := q.db.QueryRow(ctx, userByHandle, handle)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.CreatedAt,
		&i.HandleSetAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, email, handle, created_at, handle_set_at FROM users WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Handle,
		&i.CreatedAt,
		&i.HandleSetAt,
	)
	return i, err
}
