// The feed is the one place where one user's writing is shown to everybody:
// a public category name goes out under a username, unmoderated and with
// nobody to report it to. So it gets a wordlist, and anything it matches is
// dropped from the feed whole (see `isShowable` in ./presence).
//
// `./profanity.json` is generated by `scripts/build-profanity.ts` from five
// public wordlists, minus the many entries those carry that are not profanity
// at all — literal animals, ethnicities, drugs, clinical anatomy, and ordinary
// verbs like «کردن». A dropped item costs a real person their spot in the feed,
// so ambiguity is resolved in favour of showing. Add words there, not here.

import words from "./profanity.json";

/** Arabic-block letters that Persian typing produces interchangeably. */
const UNIFY: Record<string, string> = {
  "ي": "ی", // ي → ی
  "ى": "ی", // ى → ی
  "ئ": "ی", // ئ → ی
  "ك": "ک", // ك → ک
  "ة": "ه", // ة → ه
  "ۀ": "ه", // ۀ → ه
  "آ": "ا", // آ → ا
  "أ": "ا", // أ → ا
  "إ": "ا", // إ → ا
  "ؤ": "و", // ؤ → و
};

const MARKS = /[ً-ْـ‍-‏]/g;
/** Anything that is not a Persian or Latin letter separates one word from the next. */
const SEPARATORS = /[^؀-ۿa-z]+/g;
/** «سکسیییی» is «سکسی» stretched, not a different word. */
const STRETCHED = /(.)\1{2,}/g;

/**
 * Fold away every way of writing the same word: keyboard-dependent letters,
 * vowel marks, the zero-width non-joiner that splits a compound word in the
 * middle, and Persian digits. Punctuation and digits become spaces so that
 * `.کیر` and `کیر!` tokenize to the same thing as the bare word.
 *
 * Exported for `scripts/build-profanity.ts`, which has to fold the wordlist
 * exactly the way this folds the text it is matched against.
 */
export function normalize(text: string): string {
  return text
    .toLowerCase()
    .replace(/[؀-ۿ]/g, (c) => UNIFY[c] ?? c)
    .replace(MARKS, "")
    .replace(/‌/g, " ")
    .replace(/[۰-۹٠-٩]/g, " ")
    .replace(SEPARATORS, " ")
    .replace(STRETCHED, "$1")
    .trim();
}

/**
 * Persian suffixes that inflect a noun without making it a different word, so
 * one entry covers «کیر»، «کیری»، «کیرم». Deliberately excludes the bare «ه» and
 * «ا», which turn «کوس» into «کوسه» (a shark) and would cost more than they win.
 */
const SUFFIXES = [
  "", "ی", "ها", "های", "هایی", "م", "ت", "ش", "ام", "ات", "اش",
  "مون", "تون", "شون", "مان", "تان", "شان", "یم", "ید", "ند", "یی",
];

/** Below this, a word is too short for suffixes: «کس» + «ی» is «کسی», i.e. "someone". */
const INFLECT_MIN = 3;
/**
 * Below this, a word may not be matched inside a longer one: «کونده» sits in
 * «ترکونده» ("smashed it") and «اشغال» in «اشغالگر» ("occupier"). Above it,
 * nothing innocent contains the term.
 */
const SUBSTRING_MIN = 6;

// The owner's blocked names match exactly like the profanity does; they are
// kept apart in the file only so nobody has to guess which list a word is on.
const TERMS: string[][] = [...words.fa, ...words.faBlocked].map((term) => term.split(" "));
/** The handful of real words that survive every rule above: «اسکل» + «ت» is a skeleton. */
const ALLOWED = new Set(words.faAllow);
const LATIN_WORDS = new Set(words.latinWords);

/**
 * `س ک س` and `k_o_s` are one word spelled out. A run of single letters joins
 * into the word it spells, as an extra token rather than a replacement, so the
 * separators a run sits between still read as separators.
 */
function spelledOut(tokens: string[]): string[] {
  const out = [...tokens];
  let run: string[] = [];
  const flush = () => {
    // Two in a row is «کس و کیر» losing its و, not someone spelling something.
    if (run.length > 2) out.push(run.join(""));
    run = [];
  };
  for (const token of tokens) {
    if (token.length === 1) run.push(token);
    else flush();
  }
  flush();
  return out;
}

/** Does this one word carry `term`, in any of the forms that are still that word? */
function carries(word: string, term: string): boolean {
  if (word === term) return true;
  if (term.length < INFLECT_MIN) return false;
  if (term.length >= SUBSTRING_MIN && word.includes(term)) return true;
  return SUFFIXES.some((suffix) => word === term + suffix);
}

/** A multi-word term also counts when it is typed as one word: «کس کش» / «کسکش». */
function matches(tokens: string[], parts: string[]): boolean {
  const joined = parts.join("");
  if (parts.length > 1 && tokens.some((token) => carries(token, joined))) return true;
  for (let i = 0; i + parts.length <= tokens.length; i++) {
    const head = parts.slice(0, -1).every((part, j) => tokens[i + j] === part);
    if (head && carries(tokens[i + parts.length - 1], parts[parts.length - 1])) return true;
  }
  return false;
}

/**
 * Does this text — a category name, or a username — carry profanity? Persian is
 * matched word by word; usernames are `[a-z0-9_]` only, so the Latin list is
 * what catches «سکس» spelled `sex` or `koskesh` in a handle.
 */
export function isProfane(text: string | null | undefined): boolean {
  if (!text) return false;
  const normalized = normalize(text);
  if (!normalized) return false;
  const tokens = spelledOut(normalized.split(" ")).filter((token) => !ALLOWED.has(token));
  if (tokens.some((token) => LATIN_WORDS.has(token))) return true;
  // Against the tokens as well as the whole text, or `k_o_s_k_e_s_h` would
  // slip past: the run only becomes the word it spells once it is joined.
  const haystacks = [normalized, ...tokens];
  if (words.latinParts.some((part) => haystacks.some((text) => text.includes(part)))) {
    return true;
  }
  return TERMS.some((parts) => matches(tokens, parts));
}
