// Package profanity is the single authority on whether a piece of user
// writing may be shown to strangers.
//
// Two things a user writes are public: their handle, and the name of a
// category they have marked public. Both go out under a name, unmoderated,
// with nobody to report them to — so both pass through here, at claim and at
// create/rename, and the feed drops anything that still matches as a last
// gate.
//
// Matching folds away spelling rather than comparing literally, because the
// same Persian word has many ways of being typed: on an Arabic keyboard, with
// vowel marks, split by a zero-width non-joiner, stretched, spelled out letter
// by letter, or with Persian digits standing in for letters.
//
// profanity.json is generated by cmd/build-profanity from public wordlists,
// minus the many entries those carry that are not profanity at all — literal
// animals, ethnicities, drugs, clinical anatomy, and ordinary verbs. A false
// positive takes a real person's task name away, so ambiguity resolves in
// favour of allowing. Add words in the build command, never in the JSON.
package profanity

import (
	_ "embed"
	"encoding/json"
	"strings"
	"unicode/utf8"
)

//go:embed profanity.json
var wordlistJSON []byte

// Wordlist is the generated data. It is exported for the build command, which
// writes it; nothing else needs to look inside.
type Wordlist struct {
	Fa []string `json:"fa"`
	// Not profanity — names the app's owner keeps out of a public feed. Kept
	// apart so the provenance of each entry stays honest, and matched
	// identically to everything in Fa.
	FaBlocked []string `json:"faBlocked"`
	// The handful of real words that survive every rule below: «اسکلت» is
	// «اسکل» plus a suffix, and is a skeleton.
	FaAllow []string `json:"faAllow"`
	// Latin terms short enough that matching them inside a longer word would
	// hit real names — matched as whole tokens only.
	LatinWords []string `json:"latinWords"`
	// Latin terms long enough that nothing innocent contains them.
	LatinParts []string `json:"latinParts"`
}

var (
	terms      [][]string
	allowed    map[string]bool
	latinWords map[string]bool
	latinParts []string
)

func init() {
	var w Wordlist
	if err := json.Unmarshal(wordlistJSON, &w); err != nil {
		// The file is embedded at build time, so this cannot be a runtime
		// condition — it is a broken binary, and it should not start.
		panic("profanity: unreadable wordlist: " + err.Error())
	}

	for _, term := range append(append([]string{}, w.Fa...), w.FaBlocked...) {
		terms = append(terms, strings.Split(term, " "))
	}
	allowed = set(w.FaAllow)
	latinWords = set(w.LatinWords)
	latinParts = w.LatinParts
}

func set(items []string) map[string]bool {
	m := make(map[string]bool, len(items))
	for _, item := range items {
		m[item] = true
	}
	return m
}

// Contains reports whether the text carries profanity.
//
// Persian is matched word by word. A handle is `[a-z0-9_]` by construction, so
// the Latin list is what catches «سکس» written `sex`, or `koskesh`.
func Contains(text string) bool {
	normalized := Normalize(text)
	if normalized == "" {
		return false
	}

	var tokens []string
	for _, token := range spelledOut(strings.Split(normalized, " ")) {
		if !allowed[token] {
			tokens = append(tokens, token)
		}
	}

	for _, token := range tokens {
		if latinWords[token] {
			return true
		}
	}

	// Against the tokens as well as the whole text, or `k_o_s_k_e_s_h` would
	// slip past: the run only becomes the word it spells once it is joined.
	for _, part := range latinParts {
		if strings.Contains(normalized, part) {
			return true
		}
		for _, token := range tokens {
			if strings.Contains(token, part) {
				return true
			}
		}
	}

	for _, parts := range terms {
		if matches(tokens, parts) {
			return true
		}
	}
	return false
}

// Arabic-block letters that Persian typing produces interchangeably. Which one
// you get depends on the keyboard, and no user thinks of them as different
// letters.
var unify = map[rune]rune{
	'ي': 'ی',
	'ى': 'ی',
	'ئ': 'ی',
	'ك': 'ک',
	'ة': 'ه',
	'ۀ': 'ه',
	'آ': 'ا',
	'أ': 'ا',
	'إ': 'ا',
	'ؤ': 'و',
}

// Written as escapes, not as glyphs: every rune below is invisible, and a
// source file that appears to contain nothing is not one anybody can review.
const (
	tashkeelFrom = '\u064b' // fathatan, through…
	tashkeelTo   = '\u0652' // …sukun: the vowel marks
	tatweel      = '\u0640' // stretches a joined letter without changing it
	zwnj         = '\u200c' // splits a compound word in the middle
	bidiFrom     = '\u200d' // zero-width joiner, through…
	bidiTo       = '\u200f' // …right-to-left mark
	digitFaFrom  = '\u06f0' // Persian ۰, through…
	digitFaTo    = '\u06f9' // …۹
	digitArFrom  = '\u0660' // Arabic-Indic ٠, through…
	digitArTo    = '\u0669' // …٩
	arabicFrom   = '\u0600' // the Arabic block, through…
	arabicTo     = '\u06ff' // …its end
)

// Marks are invisible and droppable without changing the word. The zero-width
// *non*-joiner is deliberately not among them: it separates the halves of a
// compound word, so it becomes a space instead.
func isMark(r rune) bool {
	return (r >= tashkeelFrom && r <= tashkeelTo) ||
		r == tatweel ||
		(r >= bidiFrom && r <= bidiTo)
}

// Persian and Arabic-Indic digits. They live inside the Arabic block, so
// without this they would survive as letters — which is the whole point of
// writing «ک۱ر».
func isDigit(r rune) bool {
	return (r >= digitFaFrom && r <= digitFaTo) || (r >= digitArFrom && r <= digitArTo)
}

func isArabic(r rune) bool { return r >= arabicFrom && r <= arabicTo }

// Normalize folds away every way of writing the same word. Punctuation and
// digits become spaces, so `.کیر` and `کیر!` tokenize to the same thing as the
// bare word.
//
// Exported because the build command has to fold the wordlist exactly the way
// this folds the text it is matched against — one function, so they cannot
// drift apart.
func Normalize(text string) string {
	var folded strings.Builder
	folded.Grow(len(text))
	for _, r := range strings.ToLower(text) {
		switch {
		case isMark(r):
			// Dropped rather than spaced: a vowel mark sits *inside* a word.
		case isDigit(r), r == zwnj:
			folded.WriteRune(' ')
		default:
			if u, ok := unify[r]; ok {
				r = u
			}
			if isArabic(r) || (r >= 'a' && r <= 'z') {
				folded.WriteRune(r)
			} else {
				// Anything else separates one word from the next.
				folded.WriteRune(' ')
			}
		}
	}
	return collapse(folded.String())
}

// collapse squeezes runs of spaces to one, then collapses any rune stretched
// to three or more into a single one — «سکسیییی» is «سکسی» stretched, not a
// different word. Two in a row survives, since a doubled letter is ordinary.
func collapse(text string) string {
	var out strings.Builder
	out.Grow(len(text))

	runes := []rune(text)
	for i := 0; i < len(runes); {
		run := 1
		for i+run < len(runes) && runes[i+run] == runes[i] {
			run++
		}
		switch {
		case runes[i] == ' ' || run >= 3:
			out.WriteRune(runes[i])
		default:
			out.WriteString(strings.Repeat(string(runes[i]), run))
		}
		i += run
	}
	return strings.TrimSpace(out.String())
}

// Persian suffixes that inflect a noun without making it a different word, so
// one entry covers «کیر»، «کیری»، «کیرم». Deliberately excludes the bare «ه» and
// «ا», which turn «کوس» into «کوسه» (a shark) and would cost more than they win.
//
// The empty suffix v1 carried is dropped: an exact match is already checked.
var suffixes = []string{
	"ی", "ها", "های", "هایی", "م", "ت", "ش", "ام", "ات", "اش",
	"مون", "تون", "شون", "مان", "تان", "شان", "یم", "ید", "ند", "یی",
}

// Below this, a word is too short to take suffixes: «کس» + «ی» is «کسی», i.e.
// "someone".
const inflectMin = 3

// Below this, a word may not be matched inside a longer one: «کونده» sits in
// «ترکونده» ("smashed it") and «اشغال» in «اشغالگر» ("occupier"). Above it,
// nothing innocent contains the term.
const substringMin = 6

// carries reports whether one word is `term`, in any of the forms that are
// still that word.
func carries(word, term string) bool {
	if word == term {
		return true
	}
	length := utf8.RuneCountInString(term)
	if length < inflectMin {
		return false
	}
	if length >= substringMin && strings.Contains(word, term) {
		return true
	}
	for _, suffix := range suffixes {
		if word == term+suffix {
			return true
		}
	}
	return false
}

// matches reports whether the tokens carry a term. A multi-word term also
// counts when it is typed as one word: «کس کش» / «کسکش».
func matches(tokens, parts []string) bool {
	if len(parts) > 1 {
		joined := strings.Join(parts, "")
		for _, token := range tokens {
			if carries(token, joined) {
				return true
			}
		}
	}

	head, last := parts[:len(parts)-1], parts[len(parts)-1]
	for i := 0; i+len(parts) <= len(tokens); i++ {
		if headMatches(tokens[i:], head) && carries(tokens[i+len(head)], last) {
			return true
		}
	}
	return false
}

func headMatches(tokens, head []string) bool {
	for j, part := range head {
		if tokens[j] != part {
			return false
		}
	}
	return true
}

// spelledOut joins runs of single letters into the word they spell — `س ک س`
// and `k_o_s` are one word, typed apart. The joined word is added as an extra
// token rather than replacing the run, so the separators the run sits between
// still read as separators.
func spelledOut(tokens []string) []string {
	out := append([]string{}, tokens...)

	var run []string
	flush := func() {
		// Two in a row is «کس و کیر» losing its و, not someone spelling
		// something out.
		if len(run) > 2 {
			out = append(out, strings.Join(run, ""))
		}
		run = nil
	}
	for _, token := range tokens {
		if utf8.RuneCountInString(token) == 1 {
			run = append(run, token)
		} else {
			flush()
		}
	}
	flush()

	return out
}
